2018/03/12 01:57:08 [crit] 19512#0: *1 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 01:57:08 [error] 19512#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", upstream: "http://127.0.0.1:9000/goods/", host: "192.168.3.8:8080"
2018/03/12 01:57:08 [crit] 19512#0: *1 stat() "/home/wp/桌面/pycharm/16/shopping/www/favicon.ico" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 01:57:08 [error] 19512#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9000/favicon.ico", host: "192.168.3.8:8080"
2018/03/12 01:57:14 [crit] 19512#0: *1 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 01:57:14 [error] 19512#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", upstream: "http://127.0.0.1:9000/goods/", host: "192.168.3.8:8080"
2018/03/12 01:59:33 [crit] 19580#0: *1 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 01:59:33 [error] 19580#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", upstream: "http://127.0.0.1:9000/goods/", host: "192.168.3.8:8080"
2018/03/12 02:08:49 [emerg] 19955#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:08:49 [emerg] 19955#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:08:49 [emerg] 19955#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:08:49 [emerg] 19955#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:08:49 [emerg] 19955#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:08:49 [emerg] 19955#0: still could not bind()
2018/03/12 02:09:02 [crit] 19580#0: *3 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 02:09:02 [error] 19580#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", upstream: "http://127.0.0.1:9000/goods/", host: "192.168.3.8:8080"
2018/03/12 02:09:04 [crit] 19580#0: *3 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 02:09:04 [error] 19580#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", upstream: "http://127.0.0.1:9000/goods/", host: "192.168.3.8:8080"
2018/03/12 02:09:46 [crit] 19580#0: *3 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 02:09:46 [error] 19580#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", upstream: "http://127.0.0.1:9000/goods/", host: "192.168.3.8:8080"
2018/03/12 02:13:42 [emerg] 20158#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:13:42 [emerg] 20158#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:13:42 [emerg] 20158#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:13:42 [emerg] 20158#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:13:42 [emerg] 20158#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:13:42 [emerg] 20158#0: still could not bind()
2018/03/12 02:15:02 [crit] 19580#0: *7 stat() "/home/wp/桌面/pycharm/16/shopping/www/goods/" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /goods/ HTTP/1.1", host: "192.168.3.8:8080"
2018/03/12 02:15:03 [crit] 19580#0: *7 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/css/bootstrap.css" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/css/bootstrap.css HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *10 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/css/sticky-footer.css" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/css/sticky-footer.css HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *11 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/css/navbar.css" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/css/navbar.css HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *13 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/sweetalert/dist/sweetalert.css" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/sweetalert/dist/sweetalert.css HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *15 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/js/jquery.js" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/js/jquery.js HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *17 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/js/bootstrap.js" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/js/bootstrap.js HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *7 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/sweetalert/dist/sweetalert.min.js" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/sweetalert/dist/sweetalert.min.js HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [error] 19580#0: *10 open() "/home/wp/桌面/pycharm/16/shopping/media//goods/goods_1519664135955.jpg" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /media/goods/goods_1519664135955.jpg HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [error] 19580#0: *11 open() "/home/wp/桌面/pycharm/16/shopping/media//goods/goods_1519720151361.jpg" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /media/goods/goods_1519720151361.jpg HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [error] 19580#0: *13 open() "/home/wp/桌面/pycharm/16/shopping/media//goods/goods_1519720185118.jpg" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /media/goods/goods_1519720185118.jpg HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *7 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/js/bootstrap.js" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/js/bootstrap.js HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:03 [crit] 19580#0: *7 stat() "/home/wp/桌面/pycharm/16/shopping/www/static/sweetalert/dist/sweetalert.min.js" failed (13: Permission denied), client: 192.168.3.8, server: localhost, request: "GET /static/sweetalert/dist/sweetalert.min.js HTTP/1.1", host: "192.168.3.8:8080", referrer: "http://192.168.3.8:8080/goods/"
2018/03/12 02:15:18 [emerg] 20218#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:15:18 [emerg] 20218#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:15:18 [emerg] 20218#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:15:18 [emerg] 20218#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:15:18 [emerg] 20218#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2018/03/12 02:15:18 [emerg] 20218#0: still could not bind()
2018/03/12 02:19:54 [error] 3037#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:19:54 [error] 3037#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9000/favicon.ico", host: "192.168.3.8:8080"
2018/03/12 02:20:28 [error] 3037#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "127.0.0.1:8080"
2018/03/12 02:20:28 [error] 3037#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9000/favicon.ico", host: "127.0.0.1:8080"
2018/03/12 02:21:44 [error] 3361#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "127.0.0.1:8080"
2018/03/12 02:21:46 [error] 3361#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "127.0.0.1:8080"
2018/03/12 02:21:54 [error] 3361#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:29 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:30 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:30 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:31 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:31 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:31 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:31 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:24:31 [error] 3634#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8080"
2018/03/12 02:25:01 [error] 3666#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /goods HTTP/1.1", upstream: "http://127.0.0.1:9000/goods", host: "127.0.0.1:8888"
2018/03/12 02:25:01 [error] 3666#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9000/favicon.ico", host: "127.0.0.1:8888"
2018/03/12 02:28:34 [error] 3779#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:28:37 [error] 3779#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:35 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:36 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:37 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:37 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:37 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:37 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:37 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:38 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:38 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:38 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:38 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:39 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:39 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:39 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:40 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:40 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:41 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:30:41 [error] 3846#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:31:12 [error] 3871#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:31:13 [error] 3871#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:31:13 [error] 3871#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
2018/03/12 02:31:14 [error] 3871#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.8, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "192.168.3.8:8080"
